# Site settings
title: Elem Kode
header-img: img/home-bg.png
email: leannminakim@gmail.com
copyright_name: leannkim11
description: > # this means to ignore newlines until "baseurl:"
  Dumbed-down Coding 101
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  leannkim11
learn_profile: leannkim11
email_username: leannminakim@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
